// Command emojigen writes the Slack adapter's emoji table, emoji_names.txt:
// every name Slack reports a reaction by, and the Unicode it draws, from
// iamcal/emoji-data, the data set Slack's own names come from (MIT; the
// table carries the notice). It runs by go generate, and only then reaches
// the network; the build embeds the table it wrote.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"slices"
	"strconv"
	"strings"
	"unicode"
)

// release pins the data set, so regenerating is a choice to move it.
const (
	release = "https://raw.githubusercontent.com/iamcal/emoji-data/v16.0.0/"
	source  = release + "emoji.json"
	license = release + "LICENSE"
)

type emoji struct {
	Unified        string   `json:"unified"`
	ShortName      string   `json:"short_name"`
	ShortNames     []string `json:"short_names"`
	SkinVariations map[string]struct {
		Unified string `json:"unified"`
	} `json:"skin_variations"`
}

// skinTones are Slack's suffixes for the five modifiers, by code point.
var skinTones = map[string]string{
	"1F3FB": "skin-tone-2", "1F3FC": "skin-tone-3", "1F3FD": "skin-tone-4",
	"1F3FE": "skin-tone-5", "1F3FF": "skin-tone-6",
}

func main() {
	out := flag.String("o", "emoji_names.txt", "file to write")
	flag.Parse()
	var data []emoji
	if err := json.Unmarshal(fetch(source), &data); err != nil {
		log.Fatal(err)
	}

	// One line per name: the name, a tab, the emoji. An emoji's primary
	// name comes first, so it is the one a reverse lookup finds. A name
	// with a skin tone is written out only where withTone does not
	// already draw it.
	var lines bytes.Buffer
	lines.WriteString("# Generated by emojigen from " + source + "; DO NOT EDIT.\n")
	lines.WriteString("# The emoji names are iamcal/emoji-data's, under its license:\n#\n")
	for _, line := range strings.Split(strings.TrimRight(string(fetch(license)), "\n"), "\n") {
		lines.WriteString(strings.TrimRight("# "+line, " ") + "\n")
	}
	slices.SortFunc(data, func(a, b emoji) int { return strings.Compare(a.Unified, b.Unified) })
	for _, entry := range data {
		names := append([]string{entry.ShortName}, slices.DeleteFunc(slices.Clone(entry.ShortNames),
			func(name string) bool { return name == entry.ShortName })...)
		base := decode(entry.Unified)
		for _, name := range names {
			fmt.Fprintf(&lines, "%s\t%s\n", name, base)
		}
		tones := make([]string, 0, len(entry.SkinVariations))
		for tone := range entry.SkinVariations {
			tones = append(tones, tone)
		}
		slices.Sort(tones)
		for _, tone := range tones {
			// a two-person emoji has a tone each; Slack names only one
			suffix, single := skinTones[tone]
			if !single {
				continue
			}
			toned := decode(entry.SkinVariations[tone].Unified)
			if toned == withTone(base, mustHex(tone)) {
				continue
			}
			for _, name := range names {
				fmt.Fprintf(&lines, "%s::%s\t%s\n", name, suffix, toned)
			}
		}
	}
	if err := os.WriteFile(*out, lines.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
}

// withTone is the rule the adapter applies to a name with a skin tone,
// kept identical to the adapter's: the modifier follows the first code
// point, in place of a presentation selector there.
func withTone(base string, tone rune) string {
	runes := []rune(base)
	rest := runes[1:]
	if len(rest) > 0 && rest[0] == 0xFE0F {
		rest = rest[1:]
	}
	return string(runes[0]) + string(tone) + string(rest)
}

// mustHex parses a code point; 21 bits bound it to Unicode's range.
func mustHex(part string) rune {
	code, err := strconv.ParseUint(part, 16, 21)
	if err != nil {
		log.Fatalf("code point %q: %v", part, err)
	}
	if code > unicode.MaxRune {
		log.Fatalf("code point %q is past Unicode's range", part)
	}
	return rune(code)
}

func fetch(url string) []byte {
	resp, err := http.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("%s: %s", url, resp.Status)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	return body
}

// decode turns emoji-data's "1F44D-1F3FB" into the string it names.
func decode(unified string) string {
	var text strings.Builder
	for _, part := range strings.Split(unified, "-") {
		text.WriteRune(mustHex(part))
	}
	return text.String()
}
